version: "2"

services:
  nginx:
    image: nginx:1.11.1
    ports:
      - 3456:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  rsyslog:
    build: .
    volumes:
      - ./rsyslog.conf:/etc/rsyslog.conf
